version: '3.7'
services:
  service-db-maria:
    image: mariadb:10.6
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test