spring:
  datasource:
    minimum-idle: 1
    maximum-pool-size: 5
    pool-name: test
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/test
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: validate